[package]
name = "concurrent-vec"
version = "0.1.0"
authors = ["Patrick Norton <patrick.147.norton@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-epoch = "0.9.13"
